minimumReleaseAge: 20160 # 60 * 24 * 7 * 2 = do not install package releases that are not at least 2 weeks old
# DO NOT REMOVE OR MODIFY minimumReleaseAge without approval
# list packages to be excluded from minimum release limitation

packages:
  - extras/*
  - packages/*
  - packages/services/*
  - packages/utils/*
  - packages/wallet/*
  - repo/*
  - test/*

publicHoistPattern:
- "eslint"
