/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Signer, Interface, ContractEvent, Addressable } from 'ethers'
import type { EventFragment } from 'ethers/abi'
import type { Provider } from 'ethers/providers'
import type { Listener } from 'ethers/utils'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from './common'

export interface NanoUniversalDeployerInterface extends Interface {
  functions: {}

  events: {
    'Deploy(address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'Deploy'): EventFragment
}

export interface DeployEventObject {
  _addr: string
}
export type DeployEvent = TypedEvent<[string], DeployEventObject>
export type DeployEventFilter = TypedEventFilter<DeployEvent>

export interface NanoUniversalDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: NanoUniversalDeployerInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Promise<TypedListener<TEvent>[]>
  listeners(eventName?: string): Promise<Listener[]>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): Promise<this>
  removeAllListeners(eventName?: string): Promise<this>
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {}

  callStatic: {}

  filters: {
    Deploy: ContractEvent<[address: Addressable | string]>
    // 'Deploy(address)'(_addr?: null): ContractEvent
    // Deploy(_addr?: null): ContractEvent
  }

  estimateGas: {}

  populateTransaction: {}
}
