/* eslint-disable */
// arcadeum-api v0.3.0 7fad7bec0760add51591d51dbe2b9b9a5bf09ac4
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.3.0"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "7fad7bec0760add51591d51dbe2b9b9a5bf09ac4"


//
// Types
//
export enum ChainStateProp {
  UNKNOWN = 'UNKNOWN',
  LAST_BLOCK_INDEXED = 'LAST_BLOCK_INDEXED',
  LAST_EVENT_LOG_PROCESSED = 'LAST_EVENT_LOG_PROCESSED'
}

export enum ETHNetwork {
  UNKNOWN = 'UNKNOWN',
  MAINNET = 'MAINNET',
  MORDEN = 'MORDEN',
  ROPSTEN = 'ROPSTEN',
  RINKEBY = 'RINKEBY',
  GOERLI = 'GOERLI',
  KOVAN = 'KOVAN',
  GANACHE = 'GANACHE',
  MATIC = 'MATIC'
}

export enum ContractType {
  UNKNOWN = 'UNKNOWN',
  ERC20_TOKEN = 'ERC20_TOKEN',
  ERC721_TOKEN = 'ERC721_TOKEN',
  ERC1155_TOKEN = 'ERC1155_TOKEN',
  META_ERC20_WRAPPER = 'META_ERC20_WRAPPER',
  NIFTYSWAP = 'NIFTYSWAP',
  BRIDGE = 'BRIDGE'
}

export enum ContractCategory {
  UNKNOWN = 'UNKNOWN',
  COIN = 'COIN',
  COLLECTIBLE = 'COLLECTIBLE'
}

export enum EventLogType {
  UNKNOWN = 'UNKNOWN',
  BLOCK_ADDED = 'BLOCK_ADDED',
  BLOCK_REMOVED = 'BLOCK_REMOVED',
  BLOCK_UPDATED = 'BLOCK_UPDATED',
  TXN_LOG = 'TXN_LOG'
}

export enum ETHTxnStatus {
  UNKNOWN = 'UNKNOWN',
  FAILED = 'FAILED',
  PARTIALLY_FAILED = 'PARTIALLY_FAILED',
  SENT = 'SENT',
  REVERTED = 'REVERTED',
  SUCCESS = 'SUCCESS',
  FINAL = 'FINAL'
}

export enum OrderType {
  UNKNOWN = 'UNKNOWN',
  BUY = 'BUY',
  SELL = 'SELL'
}

export enum OrderStatus {
  UNKNOWN = 'UNKNOWN',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FINAL = 'FINAL'
}

export enum SortOrder {
  DESC = 'DESC',
  ASC = 'ASC'
}

export interface ChainState {
  id: number
  chainID: number
  prop: ChainStateProp
  value: number
  updatedAt: string
  createdAt: string
}

export interface WalletProof {
  address: string
  message: string
  signature: string
}

export interface Authorization {
  jwt: string
}

export interface User {
  address: string
  username: string
  
  avatar: string
  bio: string
  location: string
  locale: string
  backup?: boolean
  backupConfirmed?: boolean
  maxInvites?: number
  updatedAt?: string
  createdAt?: string
  
}

export interface Signup {
  user: User
  code?: string
  source?: string
}

export interface WalletBackup {
  accountAddress: string
  secretHash: string
  encryptedWallet: string
  userConfirmed: boolean
  updatedAt?: string
  createdAt?: string
}

export interface Friend {
  id: number
  userAddress: string
  friendAddress: string
  nickname: string
  user?: User
  createdAt?: string
}

export interface Bookmark {
  id: number
  userAddress: string
  url: string
  name: string
  thumbnailURL: string
  position: number
  createdAt?: string
}

export interface InviteResponse {
  code: string
  url: string
  email?: string
  expiresAt?: string
}

export interface InviteCode {
  
  
  usesLeft: number
  ownerAccount?: string
  email?: string
  url: string
  createdAt?: string
  expiresAt?: string
}

export interface InviteCodeAccount {
  
  claimedByUserAddress: string
  claimedAt?: string
}

export interface InviteInfo {
  expiryInHours: number
  max: number
  invites: Array<InviteCode>
}

export interface Contract {
  id: number
  alias: string
  contractAddress: string
  wrappedContractAddress: string
  type: ContractType
  network: ETHNetwork
  bytecodeHash: string
  trackUsersOnly: boolean
  category: ContractCategory
  name: string
  symbol: string
  decimals?: number
  logoURL: string
  website: string
  description: string
  ogImageURL: string
  originChainId: number
  originAddress: string
  hasMetadata?: boolean
  updatedAt: string
  createdAt: string
}

export interface Token {
  id: number
  contractID: number
  tokenID: string
  uri: string
  metadata: {[key: string]: any}
}

export interface TokenMetadata {
  name?: string
  description?: string
  image?: string
  decimals?: number
  properties?: any
}

export interface Balance {
  id: number
  contractAddress: string
  contractAlias: string
  accountAddress: string
  tokenID: string
  amountLatest: string
  amountConfirmed: string
  blockHash: string
  blockHeight: number
  
  tokenMetadata?: TokenMetadata
  updatedAt: string
  createdAt: string
}

export interface EventLog {
  id: number
  ts: string
  chainID: number
  type: EventLogType
  blockNum: number
  blockHash: string
  contractAddress: string
  txnHash: string
  txnIndex: number
  txnLogIndex: number
  data: {[key: string]: any}
}

export interface EtherBalance {
  accountAddress: string
  amountLatestWei: string
  amountConfirmedWei: string
  lastBlockHeight: number
}

export interface Order {
  
  orderID?: string
  txnHash?: string
  txnNonce?: number
  metaTxnID?: string
  txnStatus: ETHTxnStatus
  txnReceipt?: {[key: string]: any}
  txnRevertReason: string
  accountAddress: string
  shopContractAddress: string
  assetContractAddress: string
  baseContractAddress: string
  orderType: OrderType
  orderStatus: OrderStatus
  tokenIds: Array<string>
  amounts: Array<string>
  unitPrices: Array<string>
  subtotalPrice: string
  metatxFee: string
  brokerFee: string
  totalPrice: string
  gasUsed: number
  gasFeeWei: string
  updatedAt: string
  createdAt: string
}

export interface MetaTxLog {
  id: number
  txnHash?: string
  txnNonce?: number
  metaTxnID?: string
  txnStatus: ETHTxnStatus
  txnRevertReason: string
  txnArgs: {[key: string]: any}
  txnReceipt?: {[key: string]: any}
  gasLimit: number
  gasPrice: string
  gasUsed: number
  updatedAt: string
  createdAt: string
}

export interface MetaTxEntry {
  id: number
  metaTxnID: string
  txnStatus: ETHTxnStatus
  txnRevertReason: string
  index: number
  logs?: Array<any>
  updatedAt: string
  createdAt: string
}

export interface Requirement {
  app: string
  version: string
  etc: {[key: string]: string}
}

export interface Version {
  webrpcVersion: string
  schemaVersion: string
  schemaHash: string
  appVersion: string
}

export interface Page {
  pageSize?: number
  page?: number
  totalRecords?: number
  column?: string
  before?: any
  after?: any
  sort?: Array<SortBy>
}

export interface SortBy {
  column: string
  order: SortOrder
}

export interface GasReceipt {
  gasFee: string
  gasLimit: Array<string>
}

export interface MetaTxnEstimationInput {
  contract: string
  payload: string
  numSigners: number
}

export interface MetaTxnEstimationOutput {
  payload: string
  gasLimit: number
  feeAppended: boolean
}

export interface MetaTxn {
  contract: string
  input: string
  digest?: string
}

export interface TxnObj {
  to: string
  objs: Array<TxnObj>
  txnStatus: string
  txnRevertReason: string
  logs?: Array<any>
}

export interface MetaTxnReceipt {
  id: string
  status: string
  revertReason: string
  gasUsed: number
  txnReceipt: string
  batch: TxnObj
}

export interface SmartWalletContext {
  factory: string
  module: string
  guestModule: string
}

export interface TokenTransfer {
  recipientAddress: string
  tokenID: string
  tokenAmount: string
}

export interface GetNiftyswapUnitPricesRequest {
  orderType: OrderType
  ids: Array<string>
  amounts: Array<string>
}

export interface RegisterContractRequest {
  type: ContractType
  contractAddress: string
  contractAlias: string
  network: ETHNetwork
  name: string
  symbol: string
  logoURL: string
  website: string
  description: string
  ogImageURL: string
  originChainId: number
  originAddress: string
  category: ContractCategory
  decimals?: number
}

export interface Transaction {
  txnHash?: string
  metaTxnID?: string
  transfers?: Array<TxnLogTransfer>
  entries?: TxnObj
  users?: {[key: string]: TxnLogUser}
  contracts?: {[key: string]: Contract}
  tokenMetadata?: {[key: string]: {[key: string]: TokenMetadata}}
  timestamp: string
}

export interface TxnLogTransfer {
  contractAddress: string
  from: string
  to: string
  ids: Array<string>
  amounts: Array<string>
}

export interface TxnLogUser {
  username: string
}

export interface TokenBalance {
  contractAddress: string
  contractAlias: string
  logoURL: string
  originChainId: number
  originAddress: string
  website: string
  contractType: ContractType
  name: string
  symbol: string
  category: ContractCategory
  decimals?: number
  amountLatest: string
  amountConfirmed: string
}

export interface MetaTxSigner {
  address: string
  weight: number
}

export interface MetaTxSig {
  address: string
  signature: string
  digest?: string
}

export interface WalletConfigImage {
  imageHash: string
  threshold: number
  signers: Array<MetaTxSigner>
}

export interface WalletImage {
  walletAddress: string
  imageHash: string
}

export interface TransactionHistoryFilter {
  users?: Array<string>
  contractHandles?: Array<string>
}

export interface SentTransactionsFilter {
  pending: boolean
  failed: boolean
}

export interface TxnData {
  to: string
  methodName: string
  args: {[key: string]: any}
  objs: Array<TxnData>
}

export interface ArcadeumAPI {
  browserSignIn(args: BrowserSignInArgs, headers?: object): Promise<BrowserSignInReturn>
  browserLogout(headers?: object): Promise<BrowserLogoutReturn>
  appSignIn(args: AppSignInArgs, headers?: object): Promise<AppSignInReturn>
  getAuthToken(args: GetAuthTokenArgs, headers?: object): Promise<GetAuthTokenReturn>
  getSession(headers?: object): Promise<GetSessionReturn>
  createUser(args: CreateUserArgs, headers?: object): Promise<CreateUserReturn>
  createUserWithBackup(args: CreateUserWithBackupArgs, headers?: object): Promise<CreateUserWithBackupReturn>
  updateUsernameOrPassword(args: UpdateUsernameOrPasswordArgs, headers?: object): Promise<UpdateUsernameOrPasswordReturn>
  updateUserProfile(args: UpdateUserProfileArgs, headers?: object): Promise<UpdateUserProfileReturn>
  findUserByUsername(args: FindUserByUsernameArgs, headers?: object): Promise<FindUserByUsernameReturn>
  findUserByAddress(args: FindUserByAddressArgs, headers?: object): Promise<FindUserByAddressReturn>
  searchUsers(args: SearchUsersArgs, headers?: object): Promise<SearchUsersReturn>
  generateSillyName(headers?: object): Promise<GenerateSillyNameReturn>
  validateUsername(args: ValidateUsernameArgs, headers?: object): Promise<ValidateUsernameReturn>
  internalClaimAccessCode(args: InternalClaimAccessCodeArgs, headers?: object): Promise<InternalClaimAccessCodeReturn>
  walletRecover(args: WalletRecoverArgs, headers?: object): Promise<WalletRecoverReturn>
  walletSaveBackup(args: WalletSaveBackupArgs, headers?: object): Promise<WalletSaveBackupReturn>
  walletDeleteBackup(headers?: object): Promise<WalletDeleteBackupReturn>
  walletBackupConfirmation(args: WalletBackupConfirmationArgs, headers?: object): Promise<WalletBackupConfirmationReturn>
  friendList(args: FriendListArgs, headers?: object): Promise<FriendListReturn>
  getFriendByAddress(args: GetFriendByAddressArgs, headers?: object): Promise<GetFriendByAddressReturn>
  searchFriends(args: SearchFriendsArgs, headers?: object): Promise<SearchFriendsReturn>
  addFriend(args: AddFriendArgs, headers?: object): Promise<AddFriendReturn>
  updateFriendNickname(args: UpdateFriendNicknameArgs, headers?: object): Promise<UpdateFriendNicknameReturn>
  removeFriend(args: RemoveFriendArgs, headers?: object): Promise<RemoveFriendReturn>
  bookmarkList(args: BookmarkListArgs, headers?: object): Promise<BookmarkListReturn>
  addBookmark(args: AddBookmarkArgs, headers?: object): Promise<AddBookmarkReturn>
  updateBookmark(args: UpdateBookmarkArgs, headers?: object): Promise<UpdateBookmarkReturn>
  removeBookmark(args: RemoveBookmarkArgs, headers?: object): Promise<RemoveBookmarkReturn>
  reorderBookmark(args: ReorderBookmarkArgs, headers?: object): Promise<ReorderBookmarkReturn>
  fetchThumbnailForURL(args: FetchThumbnailForURLArgs, headers?: object): Promise<FetchThumbnailForURLReturn>
  getInviteInfo(headers?: object): Promise<GetInviteInfoReturn>
  createInvite(headers?: object): Promise<CreateInviteReturn>
  createInviteAndSend(args: CreateInviteAndSendArgs, headers?: object): Promise<CreateInviteAndSendReturn>
  sendInvite(args: SendInviteArgs, headers?: object): Promise<SendInviteReturn>
  getContract(args: GetContractArgs, headers?: object): Promise<GetContractReturn>
  getContractByAlias(args: GetContractByAliasArgs, headers?: object): Promise<GetContractByAliasReturn>
  getTokenContractsWithBalances(headers?: object): Promise<GetTokenContractsWithBalancesReturn>
  getTokenBalances(headers?: object): Promise<GetTokenBalancesReturn>
  registerContract(args: RegisterContractArgs, headers?: object): Promise<RegisterContractReturn>
  metaTxLogList(args: MetaTxLogListArgs, headers?: object): Promise<MetaTxLogListReturn>
  adminMetaTxLogList(args: AdminMetaTxLogListArgs, headers?: object): Promise<AdminMetaTxLogListReturn>
  transactionHistory(args: TransactionHistoryArgs, headers?: object): Promise<TransactionHistoryReturn>
  sentTransactions(args: SentTransactionsArgs, headers?: object): Promise<SentTransactionsReturn>
  accountEtherBalance(args: AccountEtherBalanceArgs, headers?: object): Promise<AccountEtherBalanceReturn>
  getAccountBalances(args: GetAccountBalancesArgs, headers?: object): Promise<GetAccountBalancesReturn>
  getBalanceUpdates(args: GetBalanceUpdatesArgs, headers?: object): Promise<GetBalanceUpdatesReturn>
  getTokenMetadata(args: GetTokenMetadataArgs, headers?: object): Promise<GetTokenMetadataReturn>
  decodeTxnData(args: DecodeTxnDataArgs, headers?: object): Promise<DecodeTxnDataReturn>
  internalForceBalanceBootstrap(args: InternalForceBalanceBootstrapArgs, headers?: object): Promise<InternalForceBalanceBootstrapReturn>
  placeOrder(args: PlaceOrderArgs, headers?: object): Promise<PlaceOrderReturn>
  listOrders(args: ListOrdersArgs, headers?: object): Promise<ListOrdersReturn>
  getOrder(args: GetOrderArgs, headers?: object): Promise<GetOrderReturn>
  getOrderByMetaTxnID(args: GetOrderByMetaTxnIDArgs, headers?: object): Promise<GetOrderByMetaTxnIDReturn>
  getOrderByID(args: GetOrderByIDArgs, headers?: object): Promise<GetOrderByIDReturn>
  getNiftyswapTokenSupply(args: GetNiftyswapTokenSupplyArgs, headers?: object): Promise<GetNiftyswapTokenSupplyReturn>
  getNiftyswapUnitPrices(args: GetNiftyswapUnitPricesArgs, headers?: object): Promise<GetNiftyswapUnitPricesReturn>
  adminOrderLogsList(args: AdminOrderLogsListArgs, headers?: object): Promise<AdminOrderLogsListReturn>
  sendMetaTxn(args: SendMetaTxnArgs, headers?: object): Promise<SendMetaTxnReturn>
  getMetaTxnNonce(args: GetMetaTxnNonceArgs, headers?: object): Promise<GetMetaTxnNonceReturn>
  getSmartWalletContext(headers?: object): Promise<GetSmartWalletContextReturn>
  getMetaTxnReceipt(args: GetMetaTxnReceiptArgs, headers?: object): Promise<GetMetaTxnReceiptReturn>
  getChainID(headers?: object): Promise<GetChainIDReturn>
  estimateMetaTxnGasReceipt(args: EstimateMetaTxnGasReceiptArgs, headers?: object): Promise<EstimateMetaTxnGasReceiptReturn>
  tokenFee(headers?: object): Promise<TokenFeeReturn>
  getEstimatedTime(headers?: object): Promise<GetEstimatedTimeReturn>
  wyreWalletOrderReserve(args: WyreWalletOrderReserveArgs, headers?: object): Promise<WyreWalletOrderReserveReturn>
  ping(headers?: object): Promise<PingReturn>
  version(headers?: object): Promise<VersionReturn>
  requirements(headers?: object): Promise<RequirementsReturn>
}

export interface BrowserSignInArgs {
  proof: WalletProof
}

export interface BrowserSignInReturn {
  status: boolean
  address: string
  user?: User  
}
export interface BrowserLogoutArgs {
}

export interface BrowserLogoutReturn {
  status: boolean  
}
export interface AppSignInArgs {
  proof: WalletProof
}

export interface AppSignInReturn {
  status: boolean
  address: string
  auth?: Authorization
  user?: User  
}
export interface GetAuthTokenArgs {
  ewtString: string
}

export interface GetAuthTokenReturn {
  status: boolean
  jwtToken: string
  address: string
  user?: User  
}
export interface GetSessionArgs {
}

export interface GetSessionReturn {
  address: string
  user?: User  
}
export interface CreateUserArgs {
  user: Signup
}

export interface CreateUserReturn {
  status: boolean
  user?: User  
}
export interface CreateUserWithBackupArgs {
  user: Signup
  encryptedWallet: string
  secretHash: string
}

export interface CreateUserWithBackupReturn {
  status: boolean
  user?: User  
}
export interface UpdateUsernameOrPasswordArgs {
  newUsername: string
  currentSecretHash?: string
  newEncryptedWallet?: string
  newSecretHash?: string
}

export interface UpdateUsernameOrPasswordReturn {
  status: boolean
  user?: User  
}
export interface UpdateUserProfileArgs {
  user: User
}

export interface UpdateUserProfileReturn {
  status: boolean
  user?: User  
}
export interface FindUserByUsernameArgs {
  filterUsername: string
}

export interface FindUserByUsernameReturn {
  status: boolean
  user?: User  
}
export interface FindUserByAddressArgs {
  filterAddress: string
}

export interface FindUserByAddressReturn {
  status: boolean
  user?: User  
}
export interface SearchUsersArgs {
  filterUsername: string
}

export interface SearchUsersReturn {
  status: boolean
  users: Array<User>  
}
export interface GenerateSillyNameArgs {
}

export interface GenerateSillyNameReturn {
  username: string  
}
export interface ValidateUsernameArgs {
  username: string
}

export interface ValidateUsernameReturn {
  status: boolean  
}
export interface InternalClaimAccessCodeArgs {
  address: string
  accessCode: string
}

export interface InternalClaimAccessCodeReturn {
  status: boolean  
}
export interface WalletRecoverArgs {
  username: string
  secretHash: string
}

export interface WalletRecoverReturn {
  encryptedWallet: string  
}
export interface WalletSaveBackupArgs {
  encryptedWallet: string
  secretHash: string
}

export interface WalletSaveBackupReturn {
  status: boolean  
}
export interface WalletDeleteBackupArgs {
}

export interface WalletDeleteBackupReturn {
  status: boolean  
}
export interface WalletBackupConfirmationArgs {
  t: boolean
}

export interface WalletBackupConfirmationReturn {
  status: boolean  
}
export interface FriendListArgs {
  page?: Page
}

export interface FriendListReturn {
  page: Page
  friends: Array<Friend>  
}
export interface GetFriendByAddressArgs {
  friendAddress: string
}

export interface GetFriendByAddressReturn {
  status: boolean
  friend: Friend  
}
export interface SearchFriendsArgs {
  filterUsername: string
}

export interface SearchFriendsReturn {
  friends: Array<Friend>  
}
export interface AddFriendArgs {
  friendAddress: string
  optionalNickname?: string
}

export interface AddFriendReturn {
  status: boolean
  friend?: Friend  
}
export interface UpdateFriendNicknameArgs {
  friendAddress: string
  nickname: string
}

export interface UpdateFriendNicknameReturn {
  status: boolean
  friend?: Friend  
}
export interface RemoveFriendArgs {
  friendAddress: string
}

export interface RemoveFriendReturn {
  status: boolean  
}
export interface BookmarkListArgs {
  page?: Page
}

export interface BookmarkListReturn {
  page: Page
  bookmarks: Array<Bookmark>  
}
export interface AddBookmarkArgs {
  bookmark: Bookmark
  afterBookmarkID?: number
}

export interface AddBookmarkReturn {
  status: boolean
  bookmark?: Bookmark  
}
export interface UpdateBookmarkArgs {
  id: number
  bookmark: Bookmark
}

export interface UpdateBookmarkReturn {
  status: boolean
  bookmark?: Bookmark  
}
export interface RemoveBookmarkArgs {
  id: number
}

export interface RemoveBookmarkReturn {
  status: boolean  
}
export interface ReorderBookmarkArgs {
  bookmarkID: number
  afterID: number
}

export interface ReorderBookmarkReturn {
  status: boolean
  bookmark?: Bookmark  
}
export interface FetchThumbnailForURLArgs {
  url: string
}

export interface FetchThumbnailForURLReturn {
  status: boolean
  thumbnailURL: string  
}
export interface GetInviteInfoArgs {
}

export interface GetInviteInfoReturn {
  inviteInfo: InviteInfo  
}
export interface CreateInviteArgs {
}

export interface CreateInviteReturn {
  invite: InviteResponse  
}
export interface CreateInviteAndSendArgs {
  email: string
}

export interface CreateInviteAndSendReturn {
  invite: InviteResponse  
}
export interface SendInviteArgs {
  email: string
  code: string
}

export interface SendInviteReturn {
  invite: InviteResponse  
}
export interface GetContractArgs {
  contractHandle: string
}

export interface GetContractReturn {
  contract: Contract  
}
export interface GetContractByAliasArgs {
  alias: string
}

export interface GetContractByAliasReturn {
  contract: Contract  
}
export interface GetTokenContractsWithBalancesArgs {
}

export interface GetTokenContractsWithBalancesReturn {
  contracts: Array<Contract>  
}
export interface GetTokenBalancesArgs {
}

export interface GetTokenBalancesReturn {
  balances: Array<TokenBalance>  
}
export interface RegisterContractArgs {
  req: RegisterContractRequest
}

export interface RegisterContractReturn {  
}
export interface MetaTxLogListArgs {
  page?: Page
}

export interface MetaTxLogListReturn {
  page: Page
  logs: Array<MetaTxLog>  
}
export interface AdminMetaTxLogListArgs {
  page?: Page
}

export interface AdminMetaTxLogListReturn {
  page: Page
  logs: Array<MetaTxLog>  
}
export interface TransactionHistoryArgs {
  filter: TransactionHistoryFilter
  page?: Page
}

export interface TransactionHistoryReturn {
  page: Page
  transactions: Array<Transaction>  
}
export interface SentTransactionsArgs {
  filter: SentTransactionsFilter
  page?: Page
}

export interface SentTransactionsReturn {
  page: Page
  transactions: Array<Transaction>  
}
export interface AccountEtherBalanceArgs {
  accountAddress: string
}

export interface AccountEtherBalanceReturn {
  balance: EtherBalance  
}
export interface GetAccountBalancesArgs {
  contractHandle: string
  accountAddress: string
  includeMetadata?: boolean
}

export interface GetAccountBalancesReturn {
  status: boolean
  balances: Array<Balance>  
}
export interface GetBalanceUpdatesArgs {
  contractHandle: string
  lastBalanceID: number
  page?: Page
}

export interface GetBalanceUpdatesReturn {
  page?: Page
  balances: Array<Balance>  
}
export interface GetTokenMetadataArgs {
  contractHandle: string
  tokenIDs: Array<string>
}

export interface GetTokenMetadataReturn {
  tokenMetadata: Array<TokenMetadata>  
}
export interface DecodeTxnDataArgs {
  input: string
}

export interface DecodeTxnDataReturn {
  res: TxnData  
}
export interface InternalForceBalanceBootstrapArgs {
  contractHandle: string
  owners: Array<string>
  tokenIDs?: Array<string>
}

export interface InternalForceBalanceBootstrapReturn {
  status: boolean
  balances: Array<Balance>  
}
export interface PlaceOrderArgs {
  metatx: MetaTxn
}

export interface PlaceOrderReturn {
  status: boolean
  metaTxnID: string
  order: Order  
}
export interface ListOrdersArgs {
  shopContractHandle: string
  page?: Page
}

export interface ListOrdersReturn {
  page: Page
  orders: Array<Order>  
}
export interface GetOrderArgs {
  txnHash: string
}

export interface GetOrderReturn {
  order?: Order  
}
export interface GetOrderByMetaTxnIDArgs {
  metaTxnID: string
}

export interface GetOrderByMetaTxnIDReturn {
  order?: Array<Order>  
}
export interface GetOrderByIDArgs {
  orderID: string
}

export interface GetOrderByIDReturn {
  order?: Order  
}
export interface GetNiftyswapTokenSupplyArgs {
  shopContractHandle: string
  ids: Array<string>
}

export interface GetNiftyswapTokenSupplyReturn {
  amounts: Array<string>  
}
export interface GetNiftyswapUnitPricesArgs {
  shopContractHandle: string
  req: GetNiftyswapUnitPricesRequest
}

export interface GetNiftyswapUnitPricesReturn {
  prices: Array<string>  
}
export interface AdminOrderLogsListArgs {
  page?: Page
}

export interface AdminOrderLogsListReturn {
  page: Page
  orders: Array<Order>  
}
export interface SendMetaTxnArgs {
  call: MetaTxn
}

export interface SendMetaTxnReturn {
  status: boolean
  txnHash: string  
}
export interface GetMetaTxnNonceArgs {
  walletContractAddress: string
}

export interface GetMetaTxnNonceReturn {
  nonce: string  
}
export interface GetSmartWalletContextArgs {
}

export interface GetSmartWalletContextReturn {
  data: SmartWalletContext  
}
export interface GetMetaTxnReceiptArgs {
  metaTxID: string
}

export interface GetMetaTxnReceiptReturn {
  receipt: MetaTxnReceipt  
}
export interface GetChainIDArgs {
}

export interface GetChainIDReturn {
  chainID: number  
}
export interface EstimateMetaTxnGasReceiptArgs {
  call: MetaTxnEstimationInput
  feeToken: string
}

export interface EstimateMetaTxnGasReceiptReturn {
  res: MetaTxnEstimationOutput  
}
export interface TokenFeeArgs {
}

export interface TokenFeeReturn {
  isFee: boolean
  fee: string  
}
export interface GetEstimatedTimeArgs {
}

export interface GetEstimatedTimeReturn {
  seconds: number  
}
export interface WyreWalletOrderReserveArgs {
  address: string
}

export interface WyreWalletOrderReserveReturn {
  reservationID: string  
}
export interface PingArgs {
}

export interface PingReturn {
  status: boolean  
}
export interface VersionArgs {
}

export interface VersionReturn {
  version: Version  
}
export interface RequirementsArgs {
}

export interface RequirementsReturn {
  reqs: Array<Requirement>  
}


  
//
// Client
//
export class ArcadeumAPI implements ArcadeumAPI {
  protected hostname: string
  protected fetch: Fetch
  protected path = '/rpc/ArcadeumAPI/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  browserSignIn = (args: BrowserSignInArgs, headers?: object): Promise<BrowserSignInReturn> => {
    return this.fetch(
      this.url('BrowserSignIn'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          address: <string>(_data.address), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  browserLogout = (headers?: object): Promise<BrowserLogoutReturn> => {
    return this.fetch(
      this.url('BrowserLogout'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  appSignIn = (args: AppSignInArgs, headers?: object): Promise<AppSignInReturn> => {
    return this.fetch(
      this.url('AppSignIn'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          address: <string>(_data.address), 
          auth: <Authorization>(_data.auth), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  getAuthToken = (args: GetAuthTokenArgs, headers?: object): Promise<GetAuthTokenReturn> => {
    return this.fetch(
      this.url('GetAuthToken'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          jwtToken: <string>(_data.jwtToken), 
          address: <string>(_data.address), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  getSession = (headers?: object): Promise<GetSessionReturn> => {
    return this.fetch(
      this.url('GetSession'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          address: <string>(_data.address), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  createUser = (args: CreateUserArgs, headers?: object): Promise<CreateUserReturn> => {
    return this.fetch(
      this.url('CreateUser'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  createUserWithBackup = (args: CreateUserWithBackupArgs, headers?: object): Promise<CreateUserWithBackupReturn> => {
    return this.fetch(
      this.url('CreateUserWithBackup'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  updateUsernameOrPassword = (args: UpdateUsernameOrPasswordArgs, headers?: object): Promise<UpdateUsernameOrPasswordReturn> => {
    return this.fetch(
      this.url('UpdateUsernameOrPassword'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  updateUserProfile = (args: UpdateUserProfileArgs, headers?: object): Promise<UpdateUserProfileReturn> => {
    return this.fetch(
      this.url('UpdateUserProfile'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  findUserByUsername = (args: FindUserByUsernameArgs, headers?: object): Promise<FindUserByUsernameReturn> => {
    return this.fetch(
      this.url('FindUserByUsername'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  findUserByAddress = (args: FindUserByAddressArgs, headers?: object): Promise<FindUserByAddressReturn> => {
    return this.fetch(
      this.url('FindUserByAddress'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          user: <User>(_data.user)
        }
      })
    })
  }
  
  searchUsers = (args: SearchUsersArgs, headers?: object): Promise<SearchUsersReturn> => {
    return this.fetch(
      this.url('SearchUsers'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          users: <Array<User>>(_data.users)
        }
      })
    })
  }
  
  generateSillyName = (headers?: object): Promise<GenerateSillyNameReturn> => {
    return this.fetch(
      this.url('GenerateSillyName'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          username: <string>(_data.username)
        }
      })
    })
  }
  
  validateUsername = (args: ValidateUsernameArgs, headers?: object): Promise<ValidateUsernameReturn> => {
    return this.fetch(
      this.url('ValidateUsername'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  internalClaimAccessCode = (args: InternalClaimAccessCodeArgs, headers?: object): Promise<InternalClaimAccessCodeReturn> => {
    return this.fetch(
      this.url('InternalClaimAccessCode'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  walletRecover = (args: WalletRecoverArgs, headers?: object): Promise<WalletRecoverReturn> => {
    return this.fetch(
      this.url('WalletRecover'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          encryptedWallet: <string>(_data.encryptedWallet)
        }
      })
    })
  }
  
  walletSaveBackup = (args: WalletSaveBackupArgs, headers?: object): Promise<WalletSaveBackupReturn> => {
    return this.fetch(
      this.url('WalletSaveBackup'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  walletDeleteBackup = (headers?: object): Promise<WalletDeleteBackupReturn> => {
    return this.fetch(
      this.url('WalletDeleteBackup'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  walletBackupConfirmation = (args: WalletBackupConfirmationArgs, headers?: object): Promise<WalletBackupConfirmationReturn> => {
    return this.fetch(
      this.url('WalletBackupConfirmation'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  friendList = (args: FriendListArgs, headers?: object): Promise<FriendListReturn> => {
    return this.fetch(
      this.url('FriendList'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          page: <Page>(_data.page), 
          friends: <Array<Friend>>(_data.friends)
        }
      })
    })
  }
  
  getFriendByAddress = (args: GetFriendByAddressArgs, headers?: object): Promise<GetFriendByAddressReturn> => {
    return this.fetch(
      this.url('GetFriendByAddress'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          friend: <Friend>(_data.friend)
        }
      })
    })
  }
  
  searchFriends = (args: SearchFriendsArgs, headers?: object): Promise<SearchFriendsReturn> => {
    return this.fetch(
      this.url('SearchFriends'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          friends: <Array<Friend>>(_data.friends)
        }
      })
    })
  }
  
  addFriend = (args: AddFriendArgs, headers?: object): Promise<AddFriendReturn> => {
    return this.fetch(
      this.url('AddFriend'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          friend: <Friend>(_data.friend)
        }
      })
    })
  }
  
  updateFriendNickname = (args: UpdateFriendNicknameArgs, headers?: object): Promise<UpdateFriendNicknameReturn> => {
    return this.fetch(
      this.url('UpdateFriendNickname'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          friend: <Friend>(_data.friend)
        }
      })
    })
  }
  
  removeFriend = (args: RemoveFriendArgs, headers?: object): Promise<RemoveFriendReturn> => {
    return this.fetch(
      this.url('RemoveFriend'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  bookmarkList = (args: BookmarkListArgs, headers?: object): Promise<BookmarkListReturn> => {
    return this.fetch(
      this.url('BookmarkList'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          page: <Page>(_data.page), 
          bookmarks: <Array<Bookmark>>(_data.bookmarks)
        }
      })
    })
  }
  
  addBookmark = (args: AddBookmarkArgs, headers?: object): Promise<AddBookmarkReturn> => {
    return this.fetch(
      this.url('AddBookmark'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          bookmark: <Bookmark>(_data.bookmark)
        }
      })
    })
  }
  
  updateBookmark = (args: UpdateBookmarkArgs, headers?: object): Promise<UpdateBookmarkReturn> => {
    return this.fetch(
      this.url('UpdateBookmark'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          bookmark: <Bookmark>(_data.bookmark)
        }
      })
    })
  }
  
  removeBookmark = (args: RemoveBookmarkArgs, headers?: object): Promise<RemoveBookmarkReturn> => {
    return this.fetch(
      this.url('RemoveBookmark'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  reorderBookmark = (args: ReorderBookmarkArgs, headers?: object): Promise<ReorderBookmarkReturn> => {
    return this.fetch(
      this.url('ReorderBookmark'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          bookmark: <Bookmark>(_data.bookmark)
        }
      })
    })
  }
  
  fetchThumbnailForURL = (args: FetchThumbnailForURLArgs, headers?: object): Promise<FetchThumbnailForURLReturn> => {
    return this.fetch(
      this.url('FetchThumbnailForURL'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          thumbnailURL: <string>(_data.thumbnailURL)
        }
      })
    })
  }
  
  getInviteInfo = (headers?: object): Promise<GetInviteInfoReturn> => {
    return this.fetch(
      this.url('GetInviteInfo'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          inviteInfo: <InviteInfo>(_data.inviteInfo)
        }
      })
    })
  }
  
  createInvite = (headers?: object): Promise<CreateInviteReturn> => {
    return this.fetch(
      this.url('CreateInvite'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          invite: <InviteResponse>(_data.invite)
        }
      })
    })
  }
  
  createInviteAndSend = (args: CreateInviteAndSendArgs, headers?: object): Promise<CreateInviteAndSendReturn> => {
    return this.fetch(
      this.url('CreateInviteAndSend'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          invite: <InviteResponse>(_data.invite)
        }
      })
    })
  }
  
  sendInvite = (args: SendInviteArgs, headers?: object): Promise<SendInviteReturn> => {
    return this.fetch(
      this.url('SendInvite'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          invite: <InviteResponse>(_data.invite)
        }
      })
    })
  }
  
  getContract = (args: GetContractArgs, headers?: object): Promise<GetContractReturn> => {
    return this.fetch(
      this.url('GetContract'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          contract: <Contract>(_data.contract)
        }
      })
    })
  }
  
  getContractByAlias = (args: GetContractByAliasArgs, headers?: object): Promise<GetContractByAliasReturn> => {
    return this.fetch(
      this.url('GetContractByAlias'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          contract: <Contract>(_data.contract)
        }
      })
    })
  }
  
  getTokenContractsWithBalances = (headers?: object): Promise<GetTokenContractsWithBalancesReturn> => {
    return this.fetch(
      this.url('GetTokenContractsWithBalances'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          contracts: <Array<Contract>>(_data.contracts)
        }
      })
    })
  }
  
  getTokenBalances = (headers?: object): Promise<GetTokenBalancesReturn> => {
    return this.fetch(
      this.url('GetTokenBalances'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          balances: <Array<TokenBalance>>(_data.balances)
        }
      })
    })
  }
  
  registerContract = (args: RegisterContractArgs, headers?: object): Promise<RegisterContractReturn> => {
    return this.fetch(
      this.url('RegisterContract'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
        }
      })
    })
  }
  
  metaTxLogList = (args: MetaTxLogListArgs, headers?: object): Promise<MetaTxLogListReturn> => {
    return this.fetch(
      this.url('MetaTxLogList'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          page: <Page>(_data.page), 
          logs: <Array<MetaTxLog>>(_data.logs)
        }
      })
    })
  }
  
  adminMetaTxLogList = (args: AdminMetaTxLogListArgs, headers?: object): Promise<AdminMetaTxLogListReturn> => {
    return this.fetch(
      this.url('AdminMetaTxLogList'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          page: <Page>(_data.page), 
          logs: <Array<MetaTxLog>>(_data.logs)
        }
      })
    })
  }
  
  transactionHistory = (args: TransactionHistoryArgs, headers?: object): Promise<TransactionHistoryReturn> => {
    return this.fetch(
      this.url('TransactionHistory'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          page: <Page>(_data.page), 
          transactions: <Array<Transaction>>(_data.transactions)
        }
      })
    })
  }
  
  sentTransactions = (args: SentTransactionsArgs, headers?: object): Promise<SentTransactionsReturn> => {
    return this.fetch(
      this.url('SentTransactions'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          page: <Page>(_data.page), 
          transactions: <Array<Transaction>>(_data.transactions)
        }
      })
    })
  }
  
  accountEtherBalance = (args: AccountEtherBalanceArgs, headers?: object): Promise<AccountEtherBalanceReturn> => {
    return this.fetch(
      this.url('AccountEtherBalance'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          balance: <EtherBalance>(_data.balance)
        }
      })
    })
  }
  
  getAccountBalances = (args: GetAccountBalancesArgs, headers?: object): Promise<GetAccountBalancesReturn> => {
    return this.fetch(
      this.url('GetAccountBalances'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          balances: <Array<Balance>>(_data.balances)
        }
      })
    })
  }
  
  getBalanceUpdates = (args: GetBalanceUpdatesArgs, headers?: object): Promise<GetBalanceUpdatesReturn> => {
    return this.fetch(
      this.url('GetBalanceUpdates'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          page: <Page>(_data.page), 
          balances: <Array<Balance>>(_data.balances)
        }
      })
    })
  }
  
  getTokenMetadata = (args: GetTokenMetadataArgs, headers?: object): Promise<GetTokenMetadataReturn> => {
    return this.fetch(
      this.url('GetTokenMetadata'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          tokenMetadata: <Array<TokenMetadata>>(_data.tokenMetadata)
        }
      })
    })
  }
  
  decodeTxnData = (args: DecodeTxnDataArgs, headers?: object): Promise<DecodeTxnDataReturn> => {
    return this.fetch(
      this.url('DecodeTxnData'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          res: <TxnData>(_data.res)
        }
      })
    })
  }
  
  internalForceBalanceBootstrap = (args: InternalForceBalanceBootstrapArgs, headers?: object): Promise<InternalForceBalanceBootstrapReturn> => {
    return this.fetch(
      this.url('InternalForceBalanceBootstrap'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          balances: <Array<Balance>>(_data.balances)
        }
      })
    })
  }
  
  placeOrder = (args: PlaceOrderArgs, headers?: object): Promise<PlaceOrderReturn> => {
    return this.fetch(
      this.url('PlaceOrder'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          metaTxnID: <string>(_data.metaTxnID), 
          order: <Order>(_data.order)
        }
      })
    })
  }
  
  listOrders = (args: ListOrdersArgs, headers?: object): Promise<ListOrdersReturn> => {
    return this.fetch(
      this.url('ListOrders'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          page: <Page>(_data.page), 
          orders: <Array<Order>>(_data.orders)
        }
      })
    })
  }
  
  getOrder = (args: GetOrderArgs, headers?: object): Promise<GetOrderReturn> => {
    return this.fetch(
      this.url('GetOrder'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          order: <Order>(_data.order)
        }
      })
    })
  }
  
  getOrderByMetaTxnID = (args: GetOrderByMetaTxnIDArgs, headers?: object): Promise<GetOrderByMetaTxnIDReturn> => {
    return this.fetch(
      this.url('GetOrderByMetaTxnID'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          order: <Array<Order>>(_data.order)
        }
      })
    })
  }
  
  getOrderByID = (args: GetOrderByIDArgs, headers?: object): Promise<GetOrderByIDReturn> => {
    return this.fetch(
      this.url('GetOrderByID'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          order: <Order>(_data.order)
        }
      })
    })
  }
  
  getNiftyswapTokenSupply = (args: GetNiftyswapTokenSupplyArgs, headers?: object): Promise<GetNiftyswapTokenSupplyReturn> => {
    return this.fetch(
      this.url('GetNiftyswapTokenSupply'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          amounts: <Array<string>>(_data.amounts)
        }
      })
    })
  }
  
  getNiftyswapUnitPrices = (args: GetNiftyswapUnitPricesArgs, headers?: object): Promise<GetNiftyswapUnitPricesReturn> => {
    return this.fetch(
      this.url('GetNiftyswapUnitPrices'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          prices: <Array<string>>(_data.prices)
        }
      })
    })
  }
  
  adminOrderLogsList = (args: AdminOrderLogsListArgs, headers?: object): Promise<AdminOrderLogsListReturn> => {
    return this.fetch(
      this.url('AdminOrderLogsList'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          page: <Page>(_data.page), 
          orders: <Array<Order>>(_data.orders)
        }
      })
    })
  }
  
  sendMetaTxn = (args: SendMetaTxnArgs, headers?: object): Promise<SendMetaTxnReturn> => {
    return this.fetch(
      this.url('SendMetaTxn'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status), 
          txnHash: <string>(_data.txnHash)
        }
      })
    })
  }
  
  getMetaTxnNonce = (args: GetMetaTxnNonceArgs, headers?: object): Promise<GetMetaTxnNonceReturn> => {
    return this.fetch(
      this.url('GetMetaTxnNonce'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          nonce: <string>(_data.nonce)
        }
      })
    })
  }
  
  getSmartWalletContext = (headers?: object): Promise<GetSmartWalletContextReturn> => {
    return this.fetch(
      this.url('GetSmartWalletContext'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          data: <SmartWalletContext>(_data.data)
        }
      })
    })
  }
  
  getMetaTxnReceipt = (args: GetMetaTxnReceiptArgs, headers?: object): Promise<GetMetaTxnReceiptReturn> => {
    return this.fetch(
      this.url('GetMetaTxnReceipt'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          receipt: <MetaTxnReceipt>(_data.receipt)
        }
      })
    })
  }
  
  getChainID = (headers?: object): Promise<GetChainIDReturn> => {
    return this.fetch(
      this.url('GetChainID'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          chainID: <number>(_data.chainID)
        }
      })
    })
  }
  
  estimateMetaTxnGasReceipt = (args: EstimateMetaTxnGasReceiptArgs, headers?: object): Promise<EstimateMetaTxnGasReceiptReturn> => {
    return this.fetch(
      this.url('EstimateMetaTxnGasReceipt'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          res: <MetaTxnEstimationOutput>(_data.res)
        }
      })
    })
  }
  
  tokenFee = (headers?: object): Promise<TokenFeeReturn> => {
    return this.fetch(
      this.url('TokenFee'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          isFee: <boolean>(_data.isFee), 
          fee: <string>(_data.fee)
        }
      })
    })
  }
  
  getEstimatedTime = (headers?: object): Promise<GetEstimatedTimeReturn> => {
    return this.fetch(
      this.url('GetEstimatedTime'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          seconds: <number>(_data.seconds)
        }
      })
    })
  }
  
  wyreWalletOrderReserve = (args: WyreWalletOrderReserveArgs, headers?: object): Promise<WyreWalletOrderReserveReturn> => {
    return this.fetch(
      this.url('WyreWalletOrderReserve'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          reservationID: <string>(_data.reservationID)
        }
      })
    })
  }
  
  ping = (headers?: object): Promise<PingReturn> => {
    return this.fetch(
      this.url('Ping'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  version = (headers?: object): Promise<VersionReturn> => {
    return this.fetch(
      this.url('Version'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          version: <Version>(_data.version)
        }
      })
    })
  }
  
  requirements = (headers?: object): Promise<RequirementsReturn> => {
    return this.fetch(
      this.url('Requirements'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          reqs: <Array<Requirement>>(_data.reqs)
        }
      })
    })
  }
  
}

  
export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status } as WebRPCError
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
