
on: [push]

name: Yarn actions

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn install --network-concurrency 1

  lint:
    name: TS lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn lint
 
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn coverage
      - uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: coverage
